---
install: true 
before_install: 
  - "wget https://raw.githubusercontent.com/creationix/nvm/v0.33.11/nvm.sh -O ~/.nvm/nvm.sh"
  - "source ~/.nvm/nvm.sh"
  - "nvm install 11"
  - "node --version"
  - "nvm install $NODE_VERSION"
env: 
  - NODE_VERSION="11.12.0"
jdk: openjdk11
language: java
script: "mvn clean install"
