--- 
matrix: 
  include: 
    - 
      before_install: 
        - "cd frontend/frontend"
      install: 
        - true
      language: node_js
      node_js: 
        - "11.12.0"
      script: 
        - "mvn clean install"
    - 
      before_install: 
        - "cd backend/"
      install: 
        - true
      jdk: openjdk11
      language: java
      script: 
        - "mvn clean install"
notifications: 
  email: false
